--CRIANDO INDEX PARA BUSCA DAS SERVEJAS
CREATE INDEX CERVEJAS_INDEX ON CERVEJA (NOME, DESCRICAO,SKU);
CREATE INDEX CERVEJAS_ESTILO_INDEX ON CERVEJA (CODIGO_ESTILO);
--CRIANDO INDEX PARA OS CLIENTES
CREATE INDEX CLIENTE_INDEX ON CLIENTE(NOME);
CREATE INDEX CLIENTE_CIDADE_INDEX ON CLIENTE(CODIGO_CIDADE);
--CRIANDO INDEX PARA VENDA
CREATE INDEX VENDA_INDEX ON VENDA(CODIGO_CLIENTE, CODIGO_USUARIO, DATA_HORA_ENTREGA);